name = "lean8july"
version = "0.1.0"
keywords = ["math"]

[[lean_exe]]
name = "lean8july_exe"
root = "Main"

[leanOptions]
pp.unicode.fun = true
autoImplicit = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.21.0"

[[lean_lib]]
name = "Lean8July"
srcDir = "." 